import type { Bindings } from "./types";

// Daily and nightly digests, generated by the cron. They are two framings of
// the memory the user already has:
//
//   * DAILY ("what you need to do") — a morning brief of what is ahead, drawn
//     from the same surfaced Currents the hub leads with, most important first.
//   * NIGHTLY ("what you did") — an evening recap of what was captured or
//     completed during the local day, drawn from the day's accepted claims.
//
// Both are stored as `memory_daily_reviews` rows (see migration 0031): a digest
// is a review with a `kind`. The pre-existing UNIQUE (uid, local_date,
// input_revision) makes generation idempotent — a fixed input_revision per kind
// means re-running the cron in the same local day inserts nothing. Delivery,
// when the user has a linked channel, is enqueued exactly once through the same
// `channel_deliveries` queue every other outbound message uses.

const DAILY_HOUR = 7;
const NIGHTLY_HOUR = 21;
const DAILY_REVISION = "worker-daily";
const NIGHTLY_REVISION = "worker-nightly";
const usersPerTick = 200;
const dailyItems = 6;
const nightlyItems = 12;
const maxBodyCharacters = 4_096;
const dayMs = 24 * 60 * 60 * 1000;

type DigestKind = "daily" | "nightly";

type LocalClock = { date: string; hour: number; dayStartMs: number };

const pad = (value: number): string => String(value).padStart(2, "0");

// The user's wall clock, from UTC plus their stored offset. `dayStartMs` is the
// UTC instant of local midnight, so the nightly window is [dayStartMs, +1 day).
export const localClock = (now: number, offsetMinutes: number): LocalClock => {
  const shifted = new Date(now + offsetMinutes * 60_000);
  const year = shifted.getUTCFullYear();
  const month = shifted.getUTCMonth();
  const day = shifted.getUTCDate();
  return {
    date: `${year}-${pad(month + 1)}-${pad(day)}`,
    hour: shifted.getUTCHours(),
    dayStartMs: Date.UTC(year, month, day) - offsetMinutes * 60_000,
  };
};

const collapse = (value: string): string =>
  value.split(/\s+/).filter(Boolean).join(" ");

type DailyRow = {
  title: string;
  instruction: string | null;
  evidence_id: string;
};

const dailyDigest = async (
  env: Bindings,
  uid: string,
): Promise<{ body: string; citations: string[] } | null> => {
  const rows = await env.DB.prepare(
    `SELECT c.title, json_extract(c.proposed_action, '$.instruction') AS instruction,
            c.evidence_id
     FROM currents c
     JOIN memory_evidence e ON e.id = c.evidence_id AND e.uid = c.uid
     JOIN memory_source_revisions r ON r.id = e.source_revision_id AND r.uid = e.uid
     JOIN memory_sources s ON s.id = r.source_id AND s.uid = r.uid
     WHERE c.uid = ?1 AND c.status IN ('surfaced', 'accepted')
       AND e.tombstoned_at IS NULL AND s.tombstoned_at IS NULL
     ORDER BY c.confidence_basis_points DESC, c.updated_at DESC, c.id ASC
     LIMIT ?2`,
  )
    .bind(uid, dailyItems)
    .all<DailyRow>();
  const items = rows.results ?? [];
  if (items.length === 0) return null;
  const lines = items.map((row, index) => {
    const title = collapse(String(row.title));
    const instruction = row.instruction
      ? collapse(String(row.instruction))
      : "";
    return instruction
      ? `${index + 1}. ${title} — ${instruction}`
      : `${index + 1}. ${title}`;
  });
  const body = `What you need to do today:\n${lines.join("\n")}`.slice(
    0,
    maxBodyCharacters,
  );
  const citations = [...new Set(items.map((row) => String(row.evidence_id)))];
  return { body, citations };
};

type NightlyRow = { content: string; evidence_id: string };

const nightlyDigest = async (
  env: Bindings,
  uid: string,
  dayStartMs: number,
): Promise<{ body: string; citations: string[] } | null> => {
  const rows = await env.DB.prepare(
    `SELECT c.content, e.id AS evidence_id
     FROM memory_claims c
     JOIN memory_claim_evidence ce ON ce.claim_id = c.id AND ce.uid = c.uid
       AND ce.relation = 'supports'
     JOIN memory_evidence e ON e.id = ce.evidence_id AND e.uid = ce.uid
     JOIN memory_source_revisions r ON r.id = e.source_revision_id AND r.uid = e.uid
     JOIN memory_sources s ON s.id = r.source_id AND s.uid = r.uid
     WHERE c.uid = ?1 AND c.status = 'accepted' AND c.retracted_at IS NULL
       AND c.recorded_at >= ?2 AND c.recorded_at < ?3
       AND (c.zkr_tier IS NULL OR c.zkr_tier != 'archive')
       AND (c.zkr_processing_state IS NULL OR c.zkr_processing_state = 'processed')
       AND e.tombstoned_at IS NULL AND s.tombstoned_at IS NULL
     ORDER BY c.recorded_at DESC, c.id ASC
     LIMIT ?4`,
  )
    .bind(uid, dayStartMs, dayStartMs + dayMs, nightlyItems)
    .all<NightlyRow>();
  const items = rows.results ?? [];
  if (items.length === 0) return null;
  const seen = new Set<string>();
  const lines: string[] = [];
  const citations: string[] = [];
  for (const row of items) {
    const content = collapse(String(row.content));
    if (content && !seen.has(content)) {
      seen.add(content);
      lines.push(`- ${content}`);
    }
    const evidenceId = String(row.evidence_id);
    if (!citations.includes(evidenceId)) citations.push(evidenceId);
  }
  const count = lines.length;
  const noun = count === 1 ? "thing" : "things";
  const body =
    `What you did today — ${count} ${noun} captured:\n${lines.join("\n")}`.slice(
      0,
      maxBodyCharacters,
    );
  return { body, citations };
};

// Stores the digest once and, when it was newly created, enqueues a single
// channel delivery for whichever channel the user has linked. Returns whether a
// new digest row was written, so the cron can account for its work.
const storeDigest = async (
  env: Bindings,
  uid: string,
  kind: DigestKind,
  localDate: string,
  digest: { body: string; citations: string[] },
  now: number,
): Promise<boolean> => {
  const revision = kind === "daily" ? DAILY_REVISION : NIGHTLY_REVISION;
  const id = crypto.randomUUID();
  const inserted = await env.DB.prepare(
    `INSERT OR IGNORE INTO memory_daily_reviews
       (id, uid, local_date, input_revision, body, kind, created_at, updated_at)
     VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?7)`,
  )
    .bind(id, uid, localDate, revision, digest.body, kind, now)
    .run();
  if (inserted.meta.changes !== 1) return false;
  const statements = digest.citations.map((evidenceId) =>
    env.DB.prepare(
      `INSERT OR IGNORE INTO memory_daily_review_citations (uid, review_id, evidence_id)
       SELECT ?1, ?2, e.id FROM memory_evidence e
       WHERE e.id = ?3 AND e.uid = ?1`,
    ).bind(uid, id, evidenceId),
  );
  const deliveryId = `digest:${kind}:${uid}:${localDate}`;
  statements.push(
    env.DB.prepare(
      `INSERT OR IGNORE INTO channel_deliveries
         (id, uid, channel, idempotency_key, channel_chat_id, text, next_attempt_at, created_at, updated_at)
       SELECT ?1, b.uid, b.channel, ?2, COALESCE(b.channel_chat_id, b.channel_user_id), ?3, ?4, ?4, ?4
       FROM channel_bindings b
       WHERE b.uid = ?5 AND b.revoked_at IS NULL
       ORDER BY b.verified_at DESC LIMIT 1`,
    ).bind(deliveryId, deliveryId, digest.body, now, uid),
  );
  if (statements.length > 0) await env.DB.batch(statements);
  return true;
};

type UserRow = { uid: string; digest_utc_offset_minutes: number };

// One cron pass: for each active user whose local clock is inside a digest
// window and who has no digest of that kind for the local day yet, generate and
// store it. Idempotent — outside the window, or once written, this is a no-op.
export const generateDueDigests = async (
  env: Bindings,
  now = Date.now(),
): Promise<void> => {
  const users = await env.DB.prepare(
    `SELECT uid, digest_utc_offset_minutes FROM users
     WHERE onboarding_completed_at IS NOT NULL
     ORDER BY uid LIMIT ?1`,
  )
    .bind(usersPerTick)
    .all<UserRow>();
  for (const user of users.results ?? []) {
    const clock = localClock(now, Number(user.digest_utc_offset_minutes) || 0);
    try {
      if (clock.hour === DAILY_HOUR) {
        const digest = await dailyDigest(env, user.uid);
        if (digest)
          await storeDigest(env, user.uid, "daily", clock.date, digest, now);
      }
      if (clock.hour === NIGHTLY_HOUR) {
        const digest = await nightlyDigest(env, user.uid, clock.dayStartMs);
        if (digest)
          await storeDigest(env, user.uid, "nightly", clock.date, digest, now);
      }
    } catch {}
  }
};
