# Merge with sysbuild.conf when building with WiFi enabled:
#   west build ... --sysbuild -- \
#     -DEXTRA_CONF_FILE=omi_wifi.conf \
#     -Domi_EXTRA_CONF_FILE=omi_wifi.conf \
#     -DSB_CONFIG_WIFI_NRF70=y
SB_CONFIG_WIFI_NRF70=y
